pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('about/', views.About.as_view(), name='about'),
    path('contacts/', views.Contacts.as_view(), name='contacts'),
]

publications/urls.py
from django.urls import path
from . import views

app_name = "publications"

urlpatterns = [
    path("", views.list_publications, name="list"),
    path('publications/<int:publication_id>/', views.publication_detail, name='publication_detail'),

    # Публикации: создание, редактирование и удаление
    path('publications/create/', views.create_publication, name='create_publication'),
    path('publications/<int:publication_id>/edit/', views.edit_publication, name='edit_publication'),
    path('publications/<int:publication_id>/delete/', views.delete_publication, name='delete_publication'),

    # Профиль пользователя
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/<str:username>/', views.profile_view, name='profile'),
]

publications_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from publications import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('publications.urls', namespace='publications')),
    path('pages/', include('pages.urls', namespace='pages')),
    path('auth/', include('django.contrib.auth.urls')),
    path(
        'auth/registration/',
        views.RegisterView.as_view(),
        name='registration'
    )
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'pages.views.page_not_found'
handler500 = 'pages.views.page_internal_server_error'

publications/models.py
from django.db import models
from django.contrib.auth import get_user_model

# Получение модели User
User = get_user_model()


class BaseModel(models.Model):
    name = models.CharField(
        max_length=255,
        verbose_name="Название",
        help_text="Введите название"
    )

    class Meta:
        abstract = True


class Category(BaseModel):
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Edition(BaseModel):
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        related_name='editions',
        verbose_name="Категория",
        help_text="Выберите категорию, к которой относится это издание"
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Издание"
        verbose_name_plural = "Издания"


class Issue(BaseModel):
    date = models.DateField(
        verbose_name="Дата выпуска",
        help_text="Укажите дату выпуска"
    )
    edition = models.ForeignKey(
        Edition,
        on_delete=models.CASCADE,
        related_name='issues',
        verbose_name="Издание",
        help_text="Выберите издание, к которому относится этот выпуск"
    )

    def __str__(self):
        return f"{self.name} ({self.edition.name})"

    class Meta:
        verbose_name = "Выпуск"
        verbose_name_plural = "Выпуски"


class Publication(models.Model):
    title = models.CharField(
        max_length=255,
        verbose_name="Название публикации",
        help_text="Введите название публикации"
    )
    authors = models.TextField(
        verbose_name="Авторы",
        help_text="Укажите авторов публикации, разделяя их запятой"
    )
    added_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='added_publications')
    issue = models.ForeignKey(
        Issue,
        on_delete=models.CASCADE,
        related_name='publications',
        verbose_name="Выпуск",
        help_text="Выберите выпуск, к которому относится эта публикация"
    )
    pages = models.CharField(
        max_length=20,
        verbose_name="Страницы",
        help_text="Укажите страницы, на которых опубликована статья"
    )
    keywords = models.TextField(
        verbose_name="Ключевые слова",
        help_text="Введите ключевые слова, разделяя их запятой"
    )
    abstract = models.TextField(
        verbose_name="Аннотация",
        help_text="Введите аннотацию публикации"
    )
    citations = models.ManyToManyField(
        'self',
        blank=True,
        related_name='cited_by',
        symmetrical=False,
        verbose_name="Цитаты",
        help_text="Выберите публикации, которые ссылаются на эту статью"
    )
    text = models.TextField(
        verbose_name="Текст публикации",
        help_text="Введите полный текст публикации"
    )
    file = models.FileField(
        null=True,
        blank=True,
        verbose_name="Файл публикации",
        help_text="Загрузите файл публикации"
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Публикация"
        verbose_name_plural = "Публикации"

publications/forms.py
from django.contrib.auth.models import User
from django.forms import ModelForm, DateInput, Textarea
from .models import Publication


class PublicationForm(ModelForm):
    class Meta:
        model = Publication
        fields = ['title', 'authors', 'issue', 'pages', 'keywords', 'abstract', 'citations', 'text', 'file']
        widgets = {
            'authors': Textarea(attrs={
                'rows': 1,
                'placeholder': 'Введите имена авторов через запятую. Например: Иванов И.И., Иванов И.И.'
            }),
            'keywords': Textarea(attrs={'rows': 3, 'placeholder': 'Введите ключевые слова, разделяя их запятой'}),
            'abstract': Textarea(attrs={'rows': 5, 'placeholder': 'Введите аннотацию публикации'}),
            'text': Textarea(attrs={'rows': 10, 'placeholder': 'Вставьте введение статьи'}),
        }


class ProfileEditForm(ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

publications/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.utils.timezone import now
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import CreateView
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.db.models import Count, Q

from .forms import ProfileEditForm, PublicationForm
from .models import Publication, Issue, Edition, Category

PER_PAGE = 5


def list_publications(request):
    # Получение фильтров из GET-запроса
    author_filter = request.GET.get("author", "").strip()
    edition_filter = request.GET.get("edition", "").strip()
    issue_filter = request.GET.get("issue", "").strip()
    category_filter = request.GET.get("category", "").strip()

    # Фильтрация публикаций
    publications = Publication.objects.all()

    if author_filter:
        publications = publications.filter(authors__icontains=author_filter)
    if issue_filter:
        publications = publications.filter(issue__id=issue_filter)
    if edition_filter:
        publications = publications.filter(issue__edition__id=edition_filter)
    if category_filter:
        publications = publications.filter(issue__edition__category__id=category_filter)

    # Получаем все необходимые данные для отображения
    authors = Publication.objects.values_list('authors', flat=True).distinct()
    editions = Edition.objects.all()
    issues = Issue.objects.all()
    categories = Category.objects.all()
    current_year = now().strftime('%Y')

    # Пагинация
    page_obj = Paginator(publications, PER_PAGE).get_page(request.GET.get('page'))

    context = {
        "publications": publications,
        "authors": authors,
        "editions": editions,
        "issues": issues,
        "categories": categories,
        "selected_filters": {
            "author": author_filter,
            "edition": edition_filter,
            "issue": issue_filter,
            "category": category_filter,
        },
        "current_year": current_year,
        'page_obj': page_obj,
    }

    return render(request, "publications/list.html", context)


def publication_detail(request, publication_id):
    publication = get_object_or_404(Publication, id=publication_id)

    issue = publication.issue
    issue_name = issue.name if issue else "Unknown Issue"

    edition = issue.edition if issue else None
    edition_name = edition.name if edition else "Unknown Edition"

    # Получаем все цитируемые публикации через ManyToMany
    citations = publication.citations.all()

    keywords_list = [keyword.strip() for keyword in publication.keywords.split(',')]

    context = {
        "publication": publication,
        "issue_name": issue_name,
        "edition_name": edition_name,
        "citations": citations,
        'keywords_list': keywords_list,
    }

    return render(request, 'publications/detail.html', context)


class RegisterView(CreateView):
    template_name = 'registration/registration_form.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('publications:list')


def profile_view(request, username):
    profile = get_object_or_404(User, username=username)

    # Фильтруем публикации, привязанные к данному пользователю
    publications = Publication.objects.filter(
        issue__date__isnull=False,
        added_by=profile  # Фильтруем по авторству пользователя
    ).select_related('issue__edition', 'issue__edition__category').order_by('-issue__date')

    # Пагинация
    page_obj = Paginator(publications, PER_PAGE).get_page(request.GET.get('page'))

    return render(request, 'publications/profile.html', {
        'profile': profile,
        'page_obj': page_obj
    })


@login_required
def edit_profile(request):
    form = ProfileEditForm(instance=request.user)

    if request.method == 'POST':
        form = ProfileEditForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect("publications:profile", username=request.user.username)

    return render(request, 'publications/user.html', {"form": form})


@login_required
def create_publication(request):
    """
    Представление для создания новой публикации.
    """
    publication_form = PublicationForm()

    if request.method == 'POST':
        publication_form = PublicationForm(request.POST, request.FILES)
        if publication_form.is_valid():
            authors_input = publication_form.cleaned_data['authors']
            authors_list = [username.strip() for username in authors_input.split(',')]

            # Создаём пользователей, если они не существуют
            valid_authors = []

            for username in authors_list:
                user, created = User.objects.get_or_create(username=username)
                valid_authors.append(user.username)

            # Сохраняем публикацию
            publication_instance = publication_form.save(commit=False)
            publication_instance.added_by = request.user  # Сохраняем пользователя, который добавил публикацию
            publication_instance.authors = ', '.join(valid_authors)  # Сохраняем авторов
            publication_instance.save()

            return redirect("publications:profile", username=request.user.username)

    return render(request, "publications/create.html", {"form": publication_form})


@login_required
def edit_publication(request, publication_id):
    """
    Представление для редактирования публикации.
    """
    publication = get_object_or_404(Publication, pk=publication_id)

    # Проверяем, что пользователь — автор публикации
    if request.user != publication.added_by:
        return redirect("publications:publication_detail", publication_id=publication_id)

    if request.method == 'POST':
        publication_form = PublicationForm(request.POST, instance=publication)
        if publication_form.is_valid():
            publication_form.save()
            return redirect("publications:publication_detail", publication_id=publication_id)
    else:
        publication_form = PublicationForm(instance=publication)

    return render(request, "publications/create.html", {"form": publication_form})


@login_required
def delete_publication(request, publication_id):
    """
    Представление для удаления публикации.
    """
    publication = get_object_or_404(Publication, pk=publication_id)

    # Если у публикации есть автор, проверяем права
    if hasattr(publication, 'author') and request.user.pk != publication.author.pk:
        return redirect("publications:detail", publication_id=publication_id)

    publication.delete()
    return redirect("publications:profile", username=request.user.username)

templates/publications/create.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
    {% if '/edit/' in request.path %}
        Редактирование публикации
    {% elif "/delete/" in request.path %}
        Удаление публикации
    {% else %}
        Добавление публикации
    {% endif %}
{% endblock %}
{% block content %}
    <main class="container mt-5" style="margin-bottom: 48px">
        <div class="col d-flex justify-content-center">
            <div class="card shadow" style="width: 60rem; border-radius: 10px;">
                <div class="create-card-header" style="border-radius: 10px 10px 0 0;">
                    <h4 class="m-0">
                        {% if '/edit/' in request.path %}
                            Редактирование публикации
                        {% elif '/delete/' in request.path %}
                            Удаление публикации
                        {% else %}
                            Добавление публикации
                        {% endif %}
                    </h4>
                </div>
                <div class="card-body p-4">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% if not '/delete/' in request.path %}
                            <div class="mb-3">
                                {% bootstrap_form form layout='horizontal' %}
                            </div>
                        {% else %}
                            <article class="mb-3">
                                <h3 class="text-primary">{{ form.instance.title }}</h3>
                                <p class="text-body">{{ form.instance.text|linebreaksbr }}</p>
                            </article>
                        {% endif %}
                        <div class="d-flex justify-content-center">
                            <button type="submit" class="btn btn-outline-dark w-100" style="font-weight: 800">
                                Отправить
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

templates/publications/detail.html
{% extends "base.html" %}

{% block title %}
    {{ publication.title }}
{% endblock %}

{% block content %}
    <div class="container my-5">
        <!-- Заголовок публикации -->
        <div class="hero-banner text-center">
            <h1 class="display-6">{{ publication.title }}</h1>
            <hr>
            <p class="lead mb-0">{{ publication.authors }}</p>
            <p class="lead mb-0">{{ edition_name }}</p>
            <p class="lead">{{ issue_name }}</p>

        </div>

        <!-- Основная информация -->
        <div class="row my-4">
            <div class="col-lg-6 mb-3">
                <h5>Основная информация</h5>
                <ul class="list-unstyled">
                    <li><strong>Страницы:</strong> {{ publication.pages }}</li>
                    <li><strong>Аннотация:</strong> {{ publication.abstract }}</li>
                </ul>
            </div>
            <div class="col-lg-6">

                <div class="d-flex flex-wrap">
                    {% for keyword in keywords_list %}
                        <span class="keywords">{{ keyword }}</span>
                    {% endfor %}
                </div>
            </div>
        </div>

        <div class="my-5">
            <h5 class="mb-4">Цитируется:</h5>
            {% if citations %}
                <div class="list-group">
                    {% for cit in citations %}
                        <a href="{% url 'publications:publication_detail' cit.id %}"
                           class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                            <div class="d-flex align-items-center">
                                <h6 class="mb-0"><strong>{{ cit.authors }}</strong> {{ cit.title }}</h6>
                                <span class="badge bg-secondary ms-3">Подробнее</span>
                            </div>
                            <small class="text-muted">{{ cit.publish_date }}</small>
                        </a>
                    {% endfor %}
                </div>
            {% else %}
                <div class="alert alert-info" role="alert">
                    Нет цитирований для данной публикации.
                </div>
            {% endif %}
        </div>


        <!-- Внешние цитаты -->
        {#    <div class="my-4">#}
        {#        <h5>Цитируется в (внешние ссылки):</h5>#}
        {#        <p>{{ publication.external_citations }}</p>#}
        {#    </div>#}

        <!-- Текст публикации -->
        <div class="my-4">
            <h5>Текст публикации</h5>
            <div class="border p-4 bg-white rounded shadow-sm publication-text">
                {{ publication.text }}
                {# {{ publication.text|truncatewords:100 }}#}
            </div>

        </div>
        {% if publication.file %}
            <a href="{{ publication.file.url }}" target="_blank">Скачать полный текст статьи</a>
        {% else %}
            <p>PDF файл не загружен.</p>
        {% endif %}


        <!-- Кнопка назад -->
        <div class="text-center my-4">
            <a href="{% url 'publications:list' %}" class="btn btn-outline-dark btn-lg">Вернуться к списку
                публикаций</a>
        </div>
    </div>

{% endblock %}

templates/publications/list.html
{% extends 'base.html' %}

{% block content %}
    <main class="container mt-5">
        <h1 class="mb-4 text-center">Список публикаций</h1>
        <div class="row">
            <!-- Панель фильтров -->
            <aside class="col-lg-3 mb-4">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <h5 class="card-title">Фильтры</h5>
                        <form method="get" action="{% url 'publications:list' %}">
                            <div class="mb-3">
                                <label for="author" class="form-label">Автор:</label>
                                <select name="author" id="author" class="form-select">
                                    <option value="">Все</option>
                                    {% for author in authors %}
                                        <option value="{{ author }}"
                                                {% if selected_filters.author == author %}selected{% endif %}>
                                            {{ author }}
                                        </option>
                                    {% endfor %}
                                </select>
                            </div>

                            <div class="mb-3">
                                <label for="edition" class="form-label">Издание:</label>
                                <select name="edition" id="edition" class="form-select">
                                    <option value="">Все</option>
                                    {% for edition in editions %}
                                        <option value="{{ edition.id }}"
                                                {% if selected_filters.edition == edition.id|stringformat:"s" %}selected{% endif %}>
                                            {{ edition.name }}
                                        </option>
                                    {% endfor %}
                                </select>
                            </div>

                            <div class="mb-3">
                                <label for="issue" class="form-label">Выпуск:</label>
                                <select name="issue" id="issue" class="form-select">
                                    <option value="">Все</option>
                                    {% for issue in issues %}
                                        <option value="{{ issue.id }}"
                                                {% if selected_filters.issue == issue.id|stringformat:"s" %}selected{% endif %}>
                                            {{ issue.name }}
                                        </option>
                                    {% endfor %}
                                </select>
                            </div>

                            <div class="mb-3">
                                <label for="category" class="form-label">Категория:</label>
                                <select name="category" id="category" class="form-select">
                                    <option value="">Все</option>
                                    {% for category in categories %}
                                        <option value="{{ category.id }}"
                                                {% if selected_filters.category == category.id|stringformat:"s" %}selected{% endif %}>
                                            {{ category.name }}
                                        </option>
                                    {% endfor %}
                                </select>
                            </div>

                            <div class="text-end">
                                <button type="submit" class="btn btn-outline-dark w-100" style="font-weight: 800">
                                    Применить
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </aside>

            <!-- Список публикаций -->
            <section class="col-lg-9">
                {% for publication in page_obj %}

                    <div class="publication-item mb-4 p-3 border rounded shadow-sm bg-white">
                        <h4>
                            <a href="{% url 'publications:publication_detail' publication.id %}"
                               class="text-decoration-none text-dark">
                                {{ publication.title }}
                            </a>
                        </h4>

                        <p class="mb-1"> {{ publication.authors }}</p>
                        <p class="mb-1"> {{ publication.abstract }}</p>

                        <div class="keywords">
                            <strong>Ключевые слова:</strong>
                            <p class="mb-1"> {{ publication.keywords }}</p>
                        </div>
                    </div>
                {% empty %}
                    <p class="text-muted">Публикации не найдены.</p>
                {% endfor %}
            </section>
        </div>

        {% if page_obj.has_other_pages %}
            <nav aria-label="Page navigation" class="my-5">
                <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}"><<</a>
                        </li>
                    {% endif %}
                    {% for i in page_obj.paginator.page_range %}
                        {% if page_obj.number == i %}
                            <li class="page-item active"><span class="page-link">{{ i }}</span></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link"
                                                 href="?page={{ page_obj.next_page_number }}">>></a>
                        </li>
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Последняя</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        {% endif %}

    </main>
{% endblock %}

templates/publications/profile.html
{% extends "base.html" %}
{% block title %}
    Страница пользователя {{ profile.username }}
{% endblock %}

{% block content %}
    <main class="container mt-5">
        <h1 class="mb-4 text-center">Страница пользователя {{ profile.username }}</h1>
        <small>
            <ul class="list-group list-group-horizontal justify-content-center mb-3">
                <li class="list-group-item text-muted">
                    Имя пользователя:
                    {% if profile.get_full_name %}
                        {{ profile.get_full_name }}
                    {% else %}
                        не указано
                    {% endif %}
                </li>
                <li class="list-group-item text-muted">Регистрация: {{ profile.date_joined|date:"d E Y" }}</li>
                <li class="list-group-item text-muted">Роль: {% if profile.is_staff %}Админ{% else %}
                    Пользователь{% endif %}</li>
            </ul>
            {% if user.is_authenticated and request.user == profile %}
                <ul class="list-group list-group-horizontal justify-content-center">
                    <a class="btn btn-outline-primary mx-1" href="{% url 'publications:edit_profile' %}">Редактировать
                        профиль</a>
                    <a class="btn btn-outline-danger mx-1" href="{% url 'password_change' %}">Изменить пароль</a>
                    <a class="btn btn-outline-success mx-1" href="{% url 'publications:create_publication' %}">Создать
                        публикацию</a>
                </ul>
            {% endif %}
        </small>
        <br>
        <h3 class="mb-5 text-center">Публикации пользователя</h3>

        {% if page_obj %}
            {% for publication in page_obj %}
                <article class="mb-5">
                    <div class="col d-flex justify-content-center">
                        <div class="card" style="width: 60rem">
                            <h5 class="create-card-header" style="border-radius: 5px 5px 0 0">{{ publication.title }}</h5>
                            <div class="card-body">


                                <h6 class="card-subtitle mb-2 text-muted">
                                    <small>
                                        Выпуск: {{ publication.issue.name }} ({{ publication.issue.date|date:"d E Y" }})<br>
                                        Страницы: {{ publication.pages }}<br>
                                        Издание: {{ publication.issue.edition.name }}<br>
                                        Категория: {{ publication.issue.edition.category.name }}
                                    </small>
                                </h6>
                                <p class="card-text">{{ publication.abstract|truncatewords:20 }}</p>
                                <div class="d-flex flex-wrap align-items-center mt-3">
                                    <a href="{% url 'publications:publication_detail' publication.id %}"
                                       class="text-decoration-none me-3 px-2 py-1 border rounded text-primary">
                                        Читать полный текст
                                    </a>
                                    {% if user == publication.added_by %}
                                        <a href="{% url 'publications:edit_publication' publication.id %}"
                                           class="text-decoration-none me-3 px-2 py-1 border rounded text-secondary">
                                            Редактировать
                                        </a>
                                        <a href="{% url 'publications:delete_publication' publication.id %}"
                                           class="text-decoration-none px-2 py-1 border rounded text-danger">
                                            Удалить
                                        </a>
                                    {% endif %}
                                </div>

                            </div>
                        </div>
                    </div>
                </article>
            {% endfor %}

            {% if page_obj.has_other_pages %}
                <nav aria-label="Page navigation" class="my-5">
                    <ul class="pagination justify-content-center">
                        {% if page_obj.has_previous %}
                            <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}"><<</a>
                            </li>
                        {% endif %}
                        {% for i in page_obj.paginator.page_range %}
                            {% if page_obj.number == i %}
                                <li class="page-item active"><span class="page-link">{{ i }}</span></li>
                            {% else %}
                                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                            {% endif %}
                        {% endfor %}
                        {% if page_obj.has_next %}
                            <li class="page-item"><a class="page-link"
                                                     href="?page={{ page_obj.next_page_number }}">>></a>
                            </li>
                            <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Последняя</a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            {% endif %}
        {% else %}
            <p class="text-center">У пользователя пока нет публикаций.</p>
        {% endif %}
    </main>
{% endblock %}

templates/publications/user.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
  Редактирование профиля
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        Редактирование профиля - {{ request.user.username }}
      </div>
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
          {% bootstrap_form form %}
          {% bootstrap_button button_type="submit" content="Отправить" %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}