pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('about/', views.About.as_view(), name='about'),
    path('contacts/', views.Contacts.as_view(), name='contacts'),
]

publications/urls.py
from django.urls import path
from . import views

app_name = "publications"

urlpatterns = [
    path("", views.list_publications, name="list"),
    path('publications/<int:publication_id>/', views.publication_detail, name='publication_detail'),

    # Публикации: создание, редактирование и удаление
    path('publications/create/', views.create_publication, name='create_publication'),
    path('publications/<int:publication_id>/edit/', views.edit_publication, name='edit_publication'),
    path('publications/<int:publication_id>/delete/', views.delete_publication, name='delete_publication'),

    # Профиль пользователя
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/<str:username>/', views.profile_view, name='profile'),
]

publications_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from publications import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('publications.urls', namespace='publications')),
    path('pages/', include('pages.urls', namespace='pages')),
    path('auth/', include('django.contrib.auth.urls')),
    path(
        'auth/registration/',
        views.RegisterView.as_view(),
        name='registration'
    )
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'pages.views.page_not_found'
handler500 = 'pages.views.page_internal_server_error'

templates/base.html
{% load static %}
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}БамБидиБидиБидиБомБом{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'favicon/site.webmanifest' %}">

</head>
<body class="bg-light">
<header>
    <nav class="container d-flex justify-content-between align-items-center">
        <a href="{% url 'publications:list' %}" class="navbar-brand">БамБидиБидиБидиБомБом</a>
        <div>
            <a href="{% url 'pages:about' %}">О проекте</a>
            <a href="{% url 'pages:contacts' %}">Контакты</a>

            {% if user.is_authenticated %}
                <a href="{% url 'publications:profile' user.username %}" class="ms-3">Профиль</a>
                <a href="{% url 'logout' %}" class="ms-3">Выйти</a>
            {% else %}
                <a href="{% url 'login' %}" class="ms-3">Войти</a>
                <a href="{% url 'registration' %}" class="ms-3">Регистрация</a>
            {% endif %}
        </div>
    </nav>
</header>

{% block content %}

{% endblock %}
<footer>
    <div class="container">
        <p>&copy; {{ current_year }} БамБидиБидиБидиБомБом. Все права защищены.</p>
        <p><a href="#">Политика конфиденциальности</a> | <a href="#">Условия использования</a></p>
    </div>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>